version: '3'

services:

  dbapp:
    image: 'neoflex-training_img'
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: neoflex-training
    depends_on:
      - db
    restart: always
    ports:
      - 8082:8080
    environment:
      - DATABASE_HOST=db

  db:
    image: postgres
    container_name: neoflex-postgres-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=nickolay
      - POSTGRES_USER=nickolay
      - POSTGRES_DB=nickolay
    ports:
      - 5432:5432

