server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/nickolay
    username: nickolay
    password: nickolay
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    org.apache.catalina.core.ContainerBase: off
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: ERROR

